---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailu.front.serviceName" . }}
  namespace: {{ include "mailu.names.namespace" . | quote }}
  labels: {{- include "mailu.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: front
    {{- if .Values.commonLabels }}
    {{- include "mailu.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.front.service.annotations }}
  annotations: {{- include "mailu.tplvalues.render" ( dict "value" .Values.front.service.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  selector: {{- include "mailu.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: front
  ports:
    - name: pop3
      port: 110
      protocol: TCP
    - name: pop3s
      port: 995
      protocol: TCP
    - name: imap
      port: 143
      protocol: TCP
    - name: imaps
      port: 993
      protocol: TCP
    - name: smtp
      port: 25
      protocol: TCP
    - name: smtps
      port: 465
      protocol: TCP
    - name: smtpd
      port: 587
      protocol: TCP
    - name: lmtp
      port: 2525
      protocol: TCP
    - name: smtp-auth
      port: 10025
      protocol: TCP
    - name: imap-auth
      port: 10143
      protocol: TCP
    - name: http
      port: 80
      protocol: TCP
    - name: sieve
      port: 14190
      protocol: TCP
    - name: https
      port: 443
      protocol: TCP
