---
{{- if .Values.clamav.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailu.clamav.serviceName" . }}
  namespace: {{ include "mailu.names.namespace" . | quote }}
  labels: {{- include "mailu.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: clamav
    {{- if .Values.commonLabels }}
    {{- include "mailu.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.clamav.service.annotations }}
  annotations: {{- include "mailu.tplvalues.render" ( dict "value" .Values.clamav.service.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  selector: {{- include "mailu.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: clamav
  ports:
    - name: clamav
      port: 3310
      targetPort: clamav
      protocol: TCP
{{- end }}
