language: generic
fail_fast: true
install:
  - >
    curl -s -L https://get.helm.sh/helm-v2.15.2-linux-amd64.tar.gz
    | tar xfvz - --strip-components=1 linux-amd64/helm
  - chmod 0700 helm
  - echo -e "$GITHUB_SSH_KEY" | base64 -d > ~/.ssh/id_rsa
  - chmod 0600 ~/.ssh/id_rsa
script:
  - set -e
  - mkdir -p out
  - ./helm init --client-only
  - git clone --branch gh-pages git@github.com:Mailu/helm-charts.git repo
  - ./helm package mailu -d repo
  - ./helm repo index --url https://mailu.github.io/helm-charts/ repo
  - cd repo
  - git add .
  - git commit -m "Travis build"
  - git push

