{{- if and .Values.persistence.single_pvc (not .Values.persistence.existingClaim) -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-storage" (include "mailu.fullname" . ) }}
  namespace: {{ include "mailu.names.namespace" . | quote }}
  labels: {{- include "mailu.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "mailu.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.persistence.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.persistence.annotations }}
    {{- include "mailu.tplvalues.render" ( dict "value" .Values.persistence.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "mailu.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- if and (.Values.persistence.storageClass) (not .Values.persistence.hostPath) }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  {{- if .Values.persistence.hostPath }}
  volumeName: {{ printf "%s-storage" (include "mailu.fullname" . ) }}
  {{- end }}
{{- end }}
