{{- if and (.Values.api.enabled) (not .Values.api.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mailu.api.secretName" . }}
  namespace: {{ include "mailu.names.namespace" . | quote }}
  labels: {{- include "mailu.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "mailu.tplvalues.render" ( dict "value" .Values.commonLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "mailu.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" . ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ include "mailu.api.secretKey" . -}}: {{ include "mailu.api.token" . }}
{{- end }}
