---
{{- if and .Values.externalRelay.host (not .Values.externalRelay.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mailu.externalRelay.secretName" . }}
  namespace: {{ include "mailu.names.namespace" . | quote }}
  labels: {{- include "mailu.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "mailu.tplvalues.render" ( dict "value" .Values.commonLabels "context" . ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "mailu.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" . ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ .Values.externalRelay.usernameKey -}}: {{ (include "mailu.externalRelay.username" . ) }}
  {{ .Values.externalRelay.passwordKey -}}: {{ (include "mailu.externalRelay.password" . ) }}
{{- end }}
