---
{{- if and (not .Values.persistence.single_pvc) (not .Values.admin.persistence.existingClaim)}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "mailu.admin.claimName" . }}
  namespace: {{ include "mailu.names.namespace" . | quote }}
  labels: {{- include "mailu.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: admin
    {{- if .Values.commonLabels }}
    {{- include "mailu.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.admin.persistence.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.admin.persistence.annotations }}
    {{- include "mailu.tplvalues.render" ( dict "value" .Values.admin.persistence.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "mailu.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.admin.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.admin.persistence.size | quote }}
  {{- if .Values.admin.persistence.storageClass }}
  storageClassName: {{ .Values.admin.persistence.storageClass }}
  {{- end }}
{{- end }}
