---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailu.admin.serviceName" . }}
  namespace: {{ include "mailu.names.namespace" . | quote }}
  labels: {{- include "mailu.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: admin
    {{- if .Values.commonLabels }}
    {{- include "mailu.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.admin.service.annotations }}
  annotations: {{- include "mailu.tplvalues.render" ( dict "value" .Values.admin.service.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  selector: {{- include "mailu.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: admin
  ports:
    - name: http
      port: {{ int (include "mailu.admin.port" .) }}
      protocol: TCP
