{{- if and .Values.dovecot.overrides .Values.dovecot.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-dovecot-override" (include "mailu.fullname" .) }}
  namespace: {{ include "mailu.names.namespace" . | quote }}
  labels: {{- include "mailu.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: dovecot
    {{- if .Values.commonLabels }}
    {{- include "mailu.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "mailu.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
{{- with .Values.dovecot.overrides }}
data:
{{- .|toYaml|nindent 2 }}
{{ end }}
{{ end }}
