---
{{- if .Values.dovecot.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailu.dovecot.serviceName" . }}
  namespace: {{ include "mailu.names.namespace" . | quote }}
  labels: {{- include "mailu.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: dovecot
    {{- if .Values.commonLabels }}
    {{- include "mailu.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.dovecot.service.annotations }}
  annotations: {{- include "mailu.tplvalues.render" ( dict "value" .Values.dovecot.service.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  selector: {{- include "mailu.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: dovecot
  ports:
    - name: imap-auth
      port: 2102
      protocol: TCP
    - name: imap-transport
      port: 2525
      protocol: TCP
    - name: imap-default
      port: 143
      protocol: TCP
    - name: pop3
      port: 110
      protocol: TCP
    - name: sieve
      port: 4190
      protocol: TCP
    {{- if .Values.dovecot.serviceMonitor.enabled }}
    - name: dovecot-metrics
      port: 9900
      protocol: TCP
    {{- end }}
{{- end }}
