{{- if and .Values.dovecot.enabled .Values.dovecot.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mailu.dovecot.serviceName" . }}
  namespace: {{ include "mailu.names.namespace" . | quote }}
  labels: {{- include "mailu.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: dovecot
    {{- if .Values.commonLabels }}
    {{- include "mailu.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.dovecot.serviceMonitor.annotations }}
  annotations: {{- include "mailu.tplvalues.render" ( dict "value" .Values.dovecot.serviceMonitor.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "mailu.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: dovecot
  namespaceSelector:
    matchNames:
      - {{ include "mailu.names.namespace" . | quote }}
  endpoints:
    - port: dovecot-metrics
      path: /metrics
      scheme: http
      {{- if .Values.dovecot.serviceMonitor.interval }}
      interval: {{ .Values.dovecot.serviceMonitor.interval }}
      {{- end }}
      {{- if .Values.dovecot.serviceMonitor.relabelings }}
      relabelings: {{- tpl (toYaml .Values.dovecot.serviceMonitor.relabelings | nindent 6) . }}
      {{- end }}
      {{- if .Values.dovecot.serviceMonitor.metricRelabelings }}
      metricRelabelings: {{- tpl (toYaml .Values.dovecot.serviceMonitor.metricRelabelings | nindent 6) . }}
      {{- end }}
{{- end }}
