---
{{- if and (not .Values.global.database.roundcube.existingSecret) .Values.webmail.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mailu.database.roundcube.secretName" . }}
  namespace: {{ include "mailu.names.namespace" . | quote }}
  labels: {{- include "mailu.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: webmail
    {{- if .Values.commonLabels }}
    {{- include "mailu.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.webmail.service.annotations }}
  annotations: {{- include "mailu.tplvalues.render" ( dict "value" .Values.webmail.service.annotations "context" $) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ include "mailu.database.roundcube.secretKey" . -}}: {{ (include "mailu.database.roundcube.password" . ) }}
{{- end }}
