---
{{- if .Values.webmail.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailu.webmail.serviceName" . }}
  namespace: {{ include "mailu.names.namespace" . | quote }}
  labels: {{- include "mailu.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: webmail
    {{- if .Values.commonLabels }}
    {{- include "mailu.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.webmail.service.annotations }}
  annotations: {{- include "mailu.tplvalues.render" ( dict "value" .Values.webmail.service.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  selector: {{- include "mailu.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: webmail
  ports:
    - name: http
      port: 80
      protocol: TCP
{{- end }}
