---
{{- if .Values.rspamd.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-rspamd" (include "mailu.fullname" .) }}
  namespace: {{ include "mailu.names.namespace" . | quote }}
  labels: {{- include "mailu.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: rspamd
    {{- if .Values.commonLabels }}
    {{- include "mailu.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "mailu.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  {{- if .Values.rspamd.updateStrategy }}
  strategy: {{- toYaml .Values.rspamd.updateStrategy | nindent 4 }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.rspamd.revisionHistoryLimit }}
  selector:
    matchLabels: {{- include "mailu.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: rspamd
  template:
    metadata:
      labels: {{- include "mailu.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: rspamd
        {{- if .Values.rspamd.podLabels }}
        {{- include "mailu.tplvalues.render" (dict "value" .Values.rspamd.podLabels "context" $) | nindent 8 }}
        {{- end }}
      {{- if .Values.rspamd.podAnnotations }}
      annotations: {{- include "mailu.tplvalues.render" ( dict "value" .Values.rspamd.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
    spec:
      {{- include "mailu.images.renderPullSecrets" (dict "images" (list .Values.rspamd.image) "context" $) | nindent 6 }}
      {{- if .Values.rspamd.hostAliases }}
      hostAliases: {{- include "mailu.tplvalues.render" (dict "value" .Values.rspamd.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.rspamd.nodeSelector }}
      nodeSelector: {{- include "mailu.tplvalues.render" (dict "value" .Values.rspamd.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.rspamd.affinity }}
      affinity: {{- include "mailu.tplvalues.render" (dict "value" .Values.rspamd.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.rspamd.tolerations }}
      tolerations: {{- include "mailu.tplvalues.render" (dict "value" .Values.rspamd.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.rspamd.priorityClassName }}
      priorityClassName: {{ .Values.rspamd.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.rspamd.schedulerName }}
      schedulerName: {{ .Values.rspamd.schedulerName | quote }}
      {{- end }}
      {{- if .Values.rspamd.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "mailu.tplvalues.render" (dict "value" .Values.rspamd.topologySpreadConstraints "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.rspamd.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.rspamd.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if .Values.rspamd.initContainers }}
      initContainers: {{- include "mailu.tplvalues.render" (dict "value" .Values.rspamd.initContainers "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.rspamd.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.rspamd.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      hostname: rspamd # https://github.com/Mailu/helm-charts/issues/95
      containers:
        - name: rspamd
          image: {{ .Values.imageRegistry }}/{{ .Values.rspamd.image.repository }}:{{ default (include "mailu.version" .) .Values.rspamd.image.tag }}
          imagePullPolicy: {{ .Values.rspamd.image.pullPolicy }}
          {{- if .Values.rspamd.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.rspamd.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              subPath: rspamd
              mountPath: /var/lib/rspamd
            - name: data
              subPath: rspamd-local.d-maps.d
              mountPath: /etc/rspamd/local.d/maps.d
            {{- if .Values.rspamd.overrides }}
            - name: overrides
              mountPath: /overrides
            {{- end }}
            {{- if .Values.rspamd.extraVolumeMounts }}
            {{- include "mailu.tplvalues.render" (dict "value" .Values.rspamd.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
          env:
            - name: LOG_LEVEL
              value: {{ default .Values.logLevel .Values.rspamd.logLevel }}
            {{- tpl (include "mailu.envvars.secrets" .) $ | nindent 12 }}
            {{- if .Values.rspamd.extraEnvVars }}
            {{- include "mailu.tplvalues.render" (dict "value" .Values.rspamd.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ printf "%s-envvars" (include "mailu.fullname" .) }}
            {{- if .Values.rspamd.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "mailu.tplvalues.render" (dict "value" .Values.rspamd.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.rspamd.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "mailu.tplvalues.render" (dict "value" .Values.rspamd.extraEnvVarsSecret "context" $) }}
            {{- end }}
          ports:
            - name: rspamd
              containerPort: 11332
              protocol: TCP
            - name: rspamd-http
              containerPort: 11334
              protocol: TCP
          {{- if .Values.rspamd.resources }}
          resources: {{- toYaml .Values.rspamd.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.rspamd.startupProbe.enabled }}
          startupProbe: {{- include "mailu.tplvalues.render" (dict "value" (omit .Values.rspamd.startupProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: rspamd-http
          {{- end }}
          {{- if .Values.rspamd.livenessProbe.enabled }}
          livenessProbe: {{- include "mailu.tplvalues.render" (dict "value" (omit .Values.rspamd.livenessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: rspamd-http
          {{- end }}
          {{- if .Values.rspamd.readinessProbe.enabled }}
          readinessProbe: {{- include "mailu.tplvalues.render" (dict "value" (omit .Values.rspamd.readinessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: rspamd-http
          {{- end }}
      {{- if .Values.rspamd.extraContainers }}
        {{- toYaml .Values.rspamd.extraContainers | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "mailu.rspamd.claimName" . }}
        {{- if .Values.rspamd.overrides }}
        - name: overrides
          configMap:
            name: {{ printf "%s-rspamd-override" (include "mailu.fullname" .) }}
        {{- end }}
        {{- if .Values.rspamd.extraVolumes }}
        {{- include "mailu.tplvalues.render" (dict "value" .Values.rspamd.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
{{ end }}
