---
{{- if .Values.rspamd.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mailu.rspamd.serviceName" . }}
  namespace: {{ include "mailu.names.namespace" . | quote }}
  labels: {{- include "mailu.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: rspamd
    {{- if .Values.commonLabels }}
    {{- include "mailu.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.rspamd.service.annotations }}
  annotations: {{- include "mailu.tplvalues.render" ( dict "value" .Values.rspamd.service.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  selector: {{- include "mailu.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: rspamd
  ports:
    - name: rspamd
      port: 11332
      protocol: TCP
    - name: rspamd-http
      protocol: TCP
      port: 11334
{{ end }}
