{{- if and .Values.rspamd.enabled .Values.rspamd.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mailu.rspamd.serviceName" . }}
  namespace: {{ include "mailu.names.namespace" . | quote }}
  labels: {{- include "mailu.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: rspamd
    {{- if .Values.commonLabels }}
    {{- include "mailu.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.rspamd.serviceMonitor.annotations }}
  annotations: {{- include "mailu.tplvalues.render" ( dict "value" .Values.rspamd.serviceMonitor.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "mailu.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: rspamd
  namespaceSelector:
    matchNames:
      - {{ include "mailu.names.namespace" . | quote }}
  endpoints:
    - port: rspamd-http
      path: /metrics
      scheme: http
      {{- if .Values.rspamd.serviceMonitor.interval }}
      interval: {{ .Values.rspamd.serviceMonitor.interval }}
      {{- end }}
      params:
        password:
          - "mailu"
      # Remove password from labels (even if hardcoded)
      relabelings:
        - action: labeldrop
          regex: "__param_password"
        {{ if .Values.rspamd.serviceMonitor.relabelings }}
        {{- include "mailu.tplvalues.render" ( dict "value" .Values.rspamd.serviceMonitor.relabelings "context" $) | nindent 8 }}
        {{- end }}
      {{- if .Values.rspamd.serviceMonitor.metricRelabelings }}
      metricRelabelings: {{- tpl (toYaml .Values.rspamd.serviceMonitor.metricRelabelings | nindent 6) . }}
      {{- end }}
{{- end }}
