# This file is derived from https://github.com/Mailu/Mailu/blob/master/docs/kubernetes/mailu/admin-ingress.yaml

{{- $fullname := (include "mailu.fullname" .) }}
{{ if .Values.ingress.externalIngress }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ $fullname }}-ingress
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ $fullname }}
    component: admin
spec:
  tls:
  - secretName: {{ $fullname }}-certificates
    hosts:
{{- range .Values.hostnames }}
    - "{{ . }}"
{{- end }}
  rules:
{{- range .Values.hostnames }}
  - host: "{{ . }}"
    http:
      paths:
      - path: "/"
        backend:
          serviceName: {{ $fullname }}-front
          servicePort: 80
{{- end }}
{{ end }}
