---
{{- if .Values.oletools.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-oletools" (include "mailu.fullname" .) }}
  namespace: {{ include "mailu.names.namespace" . | quote }}
  labels: {{- include "mailu.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: oletools
    {{- if .Values.commonLabels }}
    {{- include "mailu.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "mailu.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  {{- if .Values.oletools.updateStrategy }}
  strategy: {{- toYaml .Values.oletools.updateStrategy | nindent 4 }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.oletools.revisionHistoryLimit }}
  selector:
    matchLabels: {{- include "mailu.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: oletools
  template:
    metadata:
      labels: {{- include "mailu.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: oletools
        {{- if .Values.oletools.podLabels }}
        {{- include "mailu.tplvalues.render" (dict "value" .Values.oletools.podLabels "context" $) | nindent 8 }}
        {{- end }}
      {{- if .Values.oletools.podAnnotations }}
      annotations: {{- include "mailu.tplvalues.render" ( dict "value" .Values.oletools.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
    spec:
      {{- include "mailu.images.renderPullSecrets" (dict "images" (list .Values.oletools.image) "context" $) | nindent 6 }}
      {{- if .Values.oletools.hostAliases }}
      hostAliases: {{- include "mailu.tplvalues.render" (dict "value" .Values.oletools.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.oletools.nodeSelector }}
      nodeSelector: {{- include "mailu.tplvalues.render" (dict "value" .Values.oletools.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.oletools.affinity }}
      affinity: {{- include "mailu.tplvalues.render" (dict "value" .Values.oletools.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.oletools.tolerations }}
      tolerations: {{- include "mailu.tplvalues.render" (dict "value" .Values.oletools.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.oletools.priorityClassName }}
      priorityClassName: {{ .Values.oletools.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.oletools.schedulerName }}
      schedulerName: {{ .Values.oletools.schedulerName | quote }}
      {{- end }}
      {{- if .Values.oletools.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "mailu.tplvalues.render" (dict "value" .Values.oletools.topologySpreadConstraints "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.oletools.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.oletools.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if .Values.oletools.initContainers }}
      initContainers: {{- include "mailu.tplvalues.render" (dict "value" .Values.oletools.initContainers "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.oletools.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.oletools.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: oletools
          image: {{ .Values.imageRegistry }}/{{ .Values.oletools.image.repository }}:{{ default (include "mailu.version" .) .Values.oletools.image.tag }}
          imagePullPolicy: {{ .Values.oletools.image.pullPolicy }}
          {{- if .Values.oletools.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.oletools.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.oletools.extraVolumeMounts }}
          volumeMounts:
            {{- include "mailu.tplvalues.render" (dict "value" .Values.oletools.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
          env:
            - name: LOG_LEVEL
              value: {{ default .Values.logLevel .Values.oletools.logLevel }}
            {{- tpl (include "mailu.envvars.secrets" .) $ | nindent 12 }}
            {{- if .Values.oletools.extraEnvVars }}
            {{- include "mailu.tplvalues.render" (dict "value" .Values.oletools.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          {{- if or .Values.oletools.extraEnvVarsCM .Values.oletools.extraEnvVarsSecret }}
          envFrom:
            {{- if .Values.oletools.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "mailu.tplvalues.render" (dict "value" .Values.oletools.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.oletools.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "mailu.tplvalues.render" (dict "value" .Values.oletools.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- end }}
          ports:
            - name: olefy
              containerPort: 11343
              protocol: TCP
          {{- if .Values.oletools.resources }}
          resources: {{- toYaml .Values.oletools.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.oletools.startupProbe.enabled }}
          startupProbe: {{- include "mailu.tplvalues.render" (dict "value" (omit .Values.oletools.startupProbe "enabled") "context" $) | nindent 12 }}
            exec:
              command:
                - sh
                - -c
                - 'echo PING|nc -q1 localhost 11343|grep PONG'
          {{- end }}
          {{- if .Values.oletools.livenessProbe.enabled }}
          livenessProbe: {{- include "mailu.tplvalues.render" (dict "value" (omit .Values.oletools.livenessProbe "enabled") "context" $) | nindent 12 }}
            exec:
              command:
                - sh
                - -c
                - 'echo PING|nc -q1 localhost 11343|grep PONG'
          {{- end }}
          {{- if .Values.oletools.readinessProbe.enabled }}
          readinessProbe: {{- include "mailu.tplvalues.render" (dict "value" (omit .Values.oletools.readinessProbe "enabled") "context" $) | nindent 12 }}
            exec:
              command:
                - sh
                - -c
                - 'echo PING|nc -q1 localhost 11343|grep PONG'
          {{- end }}
      {{- if .Values.oletools.extraContainers }}
        {{- toYaml .Values.oletools.extraContainers | nindent 8 }}
      {{- end }}
      {{- if .Values.oletools.extraVolumes }}
      volumes:
        {{- include "mailu.tplvalues.render" (dict "value" .Values.oletools.extraVolumes "context" $) | nindent 8 }}
      {{- end }}
{{- end }}
