apiVersion: v2
appVersion: 2024.06.36
version: 2.2.1
name: mailu
description: This chart installs the Mailu mail system on kubernetes
home: https://mailu.io
sources:
  - https://github.com/Mailu/helm-charts/
icon: https://mailu.io/master/_images/logo.png
keywords:
  - mailu
  - mail
  - email
  - smtp
  - imap
  - pop3
  - webmail
  - postfix
  - dovecot
  - roundcube
maintainers:
  - name: Mailu
    url: https://mailu.io
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.8.0
  - condition: redis.enabled
    name: redis
    version: 17.15.*
    repository: https://charts.bitnami.com/bitnami
  - condition: postgresql.enabled
    name: postgresql
    version: 11.9.*
    repository: https://charts.bitnami.com/bitnami
  - condition: mariadb.enabled
    name: mariadb
    version: 12.2.*
    repository: https://charts.bitnami.com/bitnami
