apiVersion: v2
appVersion: 2024.06.41
version: 2.2.2
name: mailu
description: This chart installs the Mailu mail system on kubernetes
home: https://mailu.io
sources:
  - https://github.com/Mailu/helm-charts/
icon: https://mailu.io/master/_images/logo.png
keywords:
  - mailu
  - mail
  - email
  - smtp
  - imap
  - pop3
  - webmail
  - postfix
  - dovecot
  - roundcube
maintainers:
  - name: Mailu
    url: https://mailu.io
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.31.4
  - condition: redis.enabled
    name: redis
    version: 22.0.7
    repository: https://charts.bitnami.com/bitnami
  - condition: postgresql.enabled
    name: postgresql
    version: 16.7.27
    repository: https://charts.bitnami.com/bitnami
  - condition: mariadb.enabled
    name: mariadb
    version: 22.0.0
    repository: https://charts.bitnami.com/bitnami
