apiVersion: v2
# renovate: datasource=github-releases depName=Mailu/mailu
appVersion: 2024.06.46
version: 2.6.3
name: mailu
description: This chart installs the Mailu mail system on Kubernetes
home: https://mailu.io
sources:
  - https://github.com/Mailu/helm-charts/
icon: https://mailu.io/master/_images/logo.png
keywords:
  - mailu
  - mail
  - email
  - smtp
  - imap
  - pop3
  - webmail
  - postfix
  - dovecot
  - roundcube
maintainers:
  - name: Mailu
    url: https://mailu.io
dependencies:
  - condition: redis.enabled
    name: redis
    version: 22.0.7
    repository: https://charts.bitnami.com/bitnami
  - condition: postgresql.enabled
    name: postgresql
    version: 16.7.27
    repository: https://charts.bitnami.com/bitnami
  - condition: mariadb.enabled
    name: mariadb
    version: 24.0.3
    repository: https://charts.bitnami.com/bitnami
